Pr치ctica 4 de PAV - reconocimiento y verificaci칩n del locutor: /Users/davidbonet/Desktop/P4Git/src/fmatrix/fmatrix_cut.cpp File Reference
fmatrix_cut.cpp File Reference
#include <fstream>
#include <vector>
#include <string>
#include <iostream>
#include <sstream>
#include <unistd.h>
#include "matrix.h"
Functions
int usage (const char *prog)
int get_options (int ArgC, const char *ArgV[], string &ifname, string &ofname, vector< unsigned int > &colsel)
int main (int argc, const char *argv[])
Function Documentation
get_options()
int get_options (int ArgC, const char * ArgV[], string & ifname, string & ofname, vector< unsigned int > & colsel)
Definition at line 18 of file fmatrix_cut.cpp.
Referenced by main().
main()
int main (int argc, const char * argv[])
Definition at line 58 of file fmatrix_cut.cpp.
References get_options(), wav2lp::ncol, and usage().
usage()
int usage (const char * prog)
Definition at line 13 of file fmatrix_cut.cpp.
Referenced by main().