Pr치ctica 4 de PAV - reconocimiento y verificaci칩n del locutor: /Users/davidbonet/Desktop/P4Git/src/gmm/gmm_classify.cpp File Reference
gmm_classify.cpp File Reference
#include <unistd.h>
#include <iostream>
#include <fstream>
#include "filename.h"
#include "gmm.h"
Functions
int usage (const char *progname, int err)
int read_options (int ArgC, const char *ArgV[], vector< Directory > &input_dirs, vector< Ext > &input_exts, vector< Directory > &gmm_dirs, vector< Ext > &gmm_exts, vector< string > &input_filenames, vector< string > &gmm_filenames)
int read_gmms (const Directory &dir, const Ext &ext, const vector< string > &gmm_filenames, vector< GMM > &vgmm)
int classify (const vector< GMM > &vgmm, const fmatrix &dat, float &maxlprob)
int main (int argc, const char *argv[])
Variables
const string DEF_FEAT_EXT = "mcp"
const string DEF_GMM_EXT = "gmc"
Function Documentation
classify()
int classify (const vector< GMM > & vgmm, const fmatrix & dat, float & maxlprob)
Definition at line 23 of file gmm_classify.cpp.
Referenced by main().
main()
int main (int argc, const char * argv[])
Read and classify files
Definition at line 42 of file gmm_classify.cpp.
References classify(), read_gmms(), read_options(), and usage().
read_gmms()
int read_gmms (const Directory & dir, const Ext & ext, const vector< string > & gmm_filenames, vector< GMM > & vgmm)
Definition at line 102 of file gmm_classify.cpp.
Referenced by main().
read_options()
int read_options (int ArgC, const char * ArgV[], vector< Directory > & input_dirs, vector< Ext > & input_exts, vector< Directory > & gmm_dirs, vector< Ext > & gmm_exts, vector< string > & input_filenames, vector< string > & gmm_filenames)
Definition at line 137 of file gmm_classify.cpp.
References DEF_FEAT_EXT, and DEF_GMM_EXT.
Referenced by main().
usage()
int usage (const char * progname, int err)
Definition at line 122 of file gmm_classify.cpp.
References DEF_FEAT_EXT, and DEF_GMM_EXT.
Referenced by main().
Variable Documentation
DEF_FEAT_EXT
const string DEF_FEAT_EXT = "mcp"
Definition at line 10 of file gmm_classify.cpp.
Referenced by read_options(), and usage().
DEF_GMM_EXT
const string DEF_GMM_EXT = "gmc"
Definition at line 11 of file gmm_classify.cpp.
Referenced by read_options(), and usage().