Pr치ctica 4 de PAV - reconocimiento y verificaci칩n del locutor: /Users/davidbonet/Desktop/P4Git/src/gmm/gmm_verify.cpp File Reference
gmm_verify.cpp File Reference
#include <unistd.h>
#include <iostream>
#include <fstream>
#include <map>
#include "filename.h"
#include "gmm.h"
Functions
int usage (const char *progname, int err)
int read_options (int ArgC, const char *ArgV[], vector< Directory > &input_dirs, vector< Ext > &input_exts, vector< Directory > &gmm_dirs, vector< Ext > &gmm_exts, vector< string > &input_filenames, vector< string > &candidates, vector< string > &gmm_filenames, string &world_name)
int read_gmms (const Directory &dir, const Ext &ext, const vector< string > &gmm_filenames, map< string, GMM > &mgmm)
float verify (const GMM &gmm_candidate, const fmatrix &dat)
float verify (const GMM &gmm_candidate, const GMM &gmm_world, const fmatrix &dat, float &lprobcand, float &lprobbackground)
int main (int argc, const char *argv[])
Variables
const string DEF_FEAT_EXT = "mcp"
const string DEF_GMM_EXT = "gmc"
Function Documentation
main()
int main (int argc, const char * argv[])
Read and verify files
Definition at line 59 of file gmm_verify.cpp.
References read_gmms(), read_options(), usage(), and verify().
read_gmms()
int read_gmms (const Directory & dir, const Ext & ext, const vector< string > & gmm_filenames, map< string, GMM > & mgmm)
Definition at line 149 of file gmm_verify.cpp.
Referenced by main().
read_options()
int read_options (int ArgC, const char * ArgV[], vector< Directory > & input_dirs, vector< Ext > & input_exts, vector< Directory > & gmm_dirs, vector< Ext > & gmm_exts, vector< string > & input_filenames, vector< string > & candidates, vector< string > & gmm_filenames, string & world_name)
Definition at line 189 of file gmm_verify.cpp.
References DEF_FEAT_EXT, and DEF_GMM_EXT.
Referenced by main().
usage()
int usage (const char * progname, int err)
Definition at line 169 of file gmm_verify.cpp.
References DEF_FEAT_EXT, and DEF_GMM_EXT.
Referenced by main().
verify() [1/2]
float verify (const GMM & gmm_candidate, const fmatrix & dat)
Definition at line 26 of file gmm_verify.cpp.
References upc::GMM::logprob().
Referenced by main().
verify() [2/2]
float verify (const GMM & gmm_candidate, const GMM & gmm_world, const fmatrix & dat, float & lprobcand, float & lprobbackground)
Definition at line 41 of file gmm_verify.cpp.
References upc::GMM::logprob().
Variable Documentation
DEF_FEAT_EXT
const string DEF_FEAT_EXT = "mcp"
Definition at line 12 of file gmm_verify.cpp.
Referenced by read_options(), and usage().
DEF_GMM_EXT
const string DEF_GMM_EXT = "gmc"
Definition at line 13 of file gmm_verify.cpp.
Referenced by read_options(), and usage().