Pr치ctica 4 de PAV - reconocimiento y verificaci칩n del locutor: /Users/davidbonet/Desktop/P4Git/src/gmm/gmm_train.cpp File Reference
gmm_train.cpp File Reference
#include <unistd.h>
#include <iostream>
#include <fstream>
#include <stdlib.h>
#include "gmm.h"
#include "filename.h"
Functions
int read_data (const string &input_directory, const string &input_extension, const vector< string > &filenames, fmatrix &dat)
int usage (const char *progname, int err)
int read_options (int ArgC, const char *ArgV[], Directory &input_dir, Ext &input_ext, vector< string > &filenames, unsigned int &nmix, string &gmm_filename, unsigned int &init_iterations, unsigned int &em_iterations, float &init_threshold, float &em_threshold, int &init_method, unsigned int &verbose)
int main (int argc, const char *argv[])
Variables
const string DEF_INPUT_EXT = "mcp"
const unsigned int DEF_ITERATIONS = 20
const float DEF_THR = 1e-3
const unsigned int DEF_NMIXTURES = 5
const string DEF_GMMFILE = "output.gmc"
Function Documentation
main()
int main (int argc, const char * argv[])
Read command line options
TODO:
[HECHO]:
Initialize GMM from data; initially, you should implement random initialization.
Other alternatives are: vq, em_split... See the options of the program and place each initicialization accordingly.
TODO:
[HECHO]:
Apply EM to estimate GMM parameters (complete the funcion in gmm.cpp)
Definition at line 27 of file gmm_train.cpp.
References upc::Filename::checkDir(), DEF_GMMFILE, DEF_INPUT_EXT, DEF_ITERATIONS, DEF_NMIXTURES, DEF_THR, upc::GMM::em(), upc::GMM::em_split(), upc::matrix< _Ty >::ncol(), upc::matrix< _Ty >::nrow(), upc::GMM::print(), upc::GMM::random_init(), read_data(), read_options(), usage(), and upc::GMM::vq_lbg().
read_data()
int read_data (const string & input_directory, const string & input_extension, const vector< string > & filenames, fmatrix & dat)
Definition at line 169 of file gmm_train.cpp.
References wav2lp::ncol, upc::matrix< _Ty >::ncol(), wav2lp::nrow, upc::matrix< _Ty >::reset(), and upc::matrix< _Ty >::resize().
Referenced by main().
read_options()
int read_options (int ArgC, const char * ArgV[], Directory & input_dir, Ext & input_ext, vector< string > & filenames, unsigned int & nmix, string & gmm_filename, unsigned int & init_iterations, unsigned int & em_iterations, float & init_threshold, float & em_threshold, int & init_method, unsigned int & verbose)
Definition at line 108 of file gmm_train.cpp.
Referenced by main().
usage()
int usage (const char * progname, int err)
Definition at line 88 of file gmm_train.cpp.
References DEF_GMMFILE, DEF_INPUT_EXT, DEF_ITERATIONS, DEF_NMIXTURES, and DEF_THR.
Referenced by main().
Variable Documentation
DEF_GMMFILE
const string DEF_GMMFILE = "output.gmc"
Definition at line 15 of file gmm_train.cpp.
Referenced by main(), and usage().
DEF_INPUT_EXT
const string DEF_INPUT_EXT = "mcp"
Definition at line 11 of file gmm_train.cpp.
Referenced by main(), and usage().
DEF_ITERATIONS
const unsigned int DEF_ITERATIONS = 20
Definition at line 12 of file gmm_train.cpp.
Referenced by main(), and usage().
DEF_NMIXTURES
const unsigned int DEF_NMIXTURES = 5
Definition at line 14 of file gmm_train.cpp.
Referenced by main(), and usage().
DEF_THR
const float DEF_THR = 1e-3
Definition at line 13 of file gmm_train.cpp.
Referenced by main(), and usage().