Pr치ctica 4 de PAV - reconocimiento y verificaci칩n del locutor: exeIterar Namespace Reference
exeIterar Namespace Reference
Variables
STARTTIME = $(date +%s)
FEAT = mfcc run_spkid train $init $VQit $VQth $TH $IT $nMix
Iterar trainworld FEAT=mfcc run_spkid trainworld $init $VQit $VQth $TH $IT $nMix.
result = $(FEAT=mfcc run_spkid classerr)
ENDTIME = $(date +%s)
CALCULATE TIME ELAPSED #######.
totalseconds = $(($ENDTIME - $STARTTIME))
seconds = $((totalseconds%60));
minutes = $((totalseconds/60%60));
hours = $((totalseconds/60/60%24));
days = $((totalseconds/60/60/24));
Variable Documentation
days
exeIterar.days = $((totalseconds/60/60/24));
Definition at line 51 of file exeIterar.sh.
ENDTIME
exeIterar.ENDTIME = $(date +%s)
CALCULATE TIME ELAPSED #######.
Definition at line 46 of file exeIterar.sh.
FEAT
exeIterar.FEAT = mfcc run_spkid train $init $VQit $VQth $TH $IT $nMix
Iterar trainworld FEAT=mfcc run_spkid trainworld $init $VQit $VQth $TH $IT $nMix.
Definition at line 26 of file exeIterar.sh.
hours
exeIterar.hours = $((totalseconds/60/60%24));
Definition at line 50 of file exeIterar.sh.
minutes
exeIterar.minutes = $((totalseconds/60%60));
Definition at line 49 of file exeIterar.sh.
result
exeIterar.result = $(FEAT=mfcc run_spkid classerr)
Definition at line 30 of file exeIterar.sh.
Referenced by main(), parse_pattern(), and docopt.transform().
seconds
exeIterar.seconds = $((totalseconds%60));
Definition at line 48 of file exeIterar.sh.
STARTTIME
exeIterar.STARTTIME = $(date +%s)
Definition at line 2 of file exeIterar.sh.
totalseconds
exeIterar.totalseconds = $(($ENDTIME - $STARTTIME))
Definition at line 47 of file exeIterar.sh.