Pr치ctica 4 de PAV - reconocimiento y verificaci칩n del locutor: plot_gmm_feat Namespace Reference
plot_gmm_feat Namespace Reference
Functions
def read_gmm (fileGMM)
def read_fmatrix (fileFM)
def pdfGMM (X, weights, means, covs)
def limsGMM (means, covs, fStd=3)
def plotGMM (fileGMM, xDim, yDim, percents, colorGmm, filesFeat=None, colorFeat=None, limits=None, subplot=111)
Variables
string USAGE
Main Program.
args = docopt(USAGE)
fileGMM = args['<file-gmm>']
filesFeat = args['<file-feat>']
xDim = int(args['--xDim'])
yDim = int(args['--yDim'])
percents = args['--percents']
colorGmm = args['--colorGMM']
colorFeat = args['--colorFEAT']
limits = args['--limits']
Function Documentation
limsGMM()
def plot_gmm_feat.limsGMM (means, covs, fStd = 3)
   Returns the maximum and minimum values of the mean plus/minus fStd
   times the standard deviation for a set of Gaussians defined by their
   means and convariances.
Definition at line 75 of file plot_gmm_feat.py.
Referenced by plotGMM().
pdfGMM()
def plot_gmm_feat.pdfGMM (X, weights, means, covs)
   Returns the probability density function (PDF) of a population X
   given a Gaussian Mixture Model (GMM) defined by its weights,
   means and covariances.
Definition at line 59 of file plot_gmm_feat.py.
Referenced by plotGMM().
plotGMM()
def plot_gmm_feat.plotGMM (fileGMM, xDim, yDim, percents, colorGmm, filesFeat = None, colorFeat = None, limits = None, subplot = 111)
Definition at line 95 of file plot_gmm_feat.py.
References anonymous_namespace{docopt_util.h}.join(), limsGMM(), pdfGMM(), read_fmatrix(), read_gmm(), and anonymous_namespace{docopt_util.h}.split().
read_fmatrix()
def plot_gmm_feat.read_fmatrix (fileFM)
   Reads an fmatrix from a file
Definition at line 44 of file plot_gmm_feat.py.
Referenced by plotGMM().
read_gmm()
def plot_gmm_feat.read_gmm (fileGMM)
   Reads the weights, means and convariances from a GMM
   stored using format "UPC: GMM V 2.0"
Definition at line 12 of file plot_gmm_feat.py.
Referenced by plotGMM().
Variable Documentation
args
plot_gmm_feat.args = docopt(USAGE)
Definition at line 183 of file plot_gmm_feat.py.
colorFeat
plot_gmm_feat.colorFeat = args['--colorFEAT']
Definition at line 194 of file plot_gmm_feat.py.
colorGmm
plot_gmm_feat.colorGmm = args['--colorGMM']
Definition at line 193 of file plot_gmm_feat.py.
fileGMM
plot_gmm_feat.fileGMM = args['<file-gmm>']
Definition at line 185 of file plot_gmm_feat.py.
filesFeat
plot_gmm_feat.filesFeat = args['<file-feat>']
Definition at line 186 of file plot_gmm_feat.py.
limits
list plot_gmm_feat.limits = args['--limits']
Definition at line 195 of file plot_gmm_feat.py.
percents
plot_gmm_feat.percents = args['--percents']
Definition at line 189 of file plot_gmm_feat.py.
USAGE
string plot_gmm_feat.USAGE
Initial value:
 = '''
 Draws the regions in space covered with a certain probability by a GMM.
 Usage:
     plotGMM [--help|-h] [options] <file-gmm> [<file-feat>...]
 Options:
     --yDim INT, -x INT               'x' dimension to use from GMM and feature vectors [default: 0]
     --xDim INT, -y INT               'y' dimension to use from GMM and feature vectors [default: 1]
     --percents FLOAT..., -p FLOAT...  Percentages covered by the regions [default: 90,50]
     --colorGMM STR, -g STR            Color of the GMM regions boundaries [default: red]
     --colorFEAT STR, -f STR           Color of the feature population [default: red]
     --limits xyLimits -l xyLimits     xyLimits are the four values xMin,xMax,yMin,yMax [default: auto]
     --help, -h                        Shows this message
 Arguments:
     <file-gmm>    File with the Gaussian mixture model to be plotted
     <file-fear>   Feature files to be plotted along the GMM
 '''
Main Program.
Definition at line 161 of file plot_gmm_feat.py.
xDim
plot_gmm_feat.xDim = int(args['--xDim'])
Definition at line 187 of file plot_gmm_feat.py.
yDim
plot_gmm_feat.yDim = int(args['--yDim'])
Definition at line 188 of file plot_gmm_feat.py.