Pr치ctica 4 de PAV - reconocimiento y verificaci칩n del locutor: plot_gmm_feat_extended Namespace Reference
plot_gmm_feat_extended Namespace Reference
Functions
def read_gmm (fileGMM)
def read_fmatrix (fileFM)
def pdfGMM (X, weights, means, covs)
def limsGMM (means, covs, fStd=3)
def plotGMM (subplot, fileGMM, xDim, yDim, percents, colorGmm, filesFeat, colorFeat=None, limits=None)
Variables
string USAGE
Main Program.
args = docopt(USAGE)
fileGMM_1 = args['<file-gmm-1>']
fileGMM_2 = args['<file-gmm-2>']
filesFeat_1 = args['<file-feat-1>']
filesFeat_2 = args['<file-feat-2>']
xDim = int(args['--xDim'])
yDim = int(args['--yDim'])
percents = args['--percents']
colorGmm = args['--colorGMM']
colorFeat = args['--colorFEAT']
limits = args['--limits']
Function Documentation
limsGMM()
def plot_gmm_feat_extended.limsGMM (means, covs, fStd = 3)
   Returns the maximum and minimum values of the mean plus/minus fStd
   times the standard deviation for a set of Gaussians defined by their
   means and convariances.
Definition at line 79 of file plot_gmm_feat_extended.py.
Referenced by plotGMM().
pdfGMM()
def plot_gmm_feat_extended.pdfGMM (X, weights, means, covs)
   Returns the probability density function (PDF) of a population X
   given a Gaussian Mixture Model (GMM) defined by its weights,
   means and covariances.
Definition at line 63 of file plot_gmm_feat_extended.py.
Referenced by plotGMM().
plotGMM()
def plot_gmm_feat_extended.plotGMM (subplot, fileGMM, xDim, yDim, percents, colorGmm, filesFeat, colorFeat = None, limits = None)
Definition at line 99 of file plot_gmm_feat_extended.py.
References anonymous_namespace{docopt_util.h}.join(), limsGMM(), pdfGMM(), read_fmatrix(), read_gmm(), and anonymous_namespace{docopt_util.h}.split().
read_fmatrix()
def plot_gmm_feat_extended.read_fmatrix (fileFM)
   Reads an fmatrix from a file
Definition at line 48 of file plot_gmm_feat_extended.py.
Referenced by plotGMM().
read_gmm()
def plot_gmm_feat_extended.read_gmm (fileGMM)
   Reads the weights, means and convariances from a GMM
   stored using format "UPC: GMM V 2.0"
Definition at line 16 of file plot_gmm_feat_extended.py.
Referenced by plotGMM().
Variable Documentation
args
plot_gmm_feat_extended.args = docopt(USAGE)
Definition at line 190 of file plot_gmm_feat_extended.py.
colorFeat
plot_gmm_feat_extended.colorFeat = args['--colorFEAT']
Definition at line 203 of file plot_gmm_feat_extended.py.
colorGmm
plot_gmm_feat_extended.colorGmm = args['--colorGMM']
Definition at line 202 of file plot_gmm_feat_extended.py.
fileGMM_1
plot_gmm_feat_extended.fileGMM_1 = args['<file-gmm-1>']
Definition at line 192 of file plot_gmm_feat_extended.py.
fileGMM_2
plot_gmm_feat_extended.fileGMM_2 = args['<file-gmm-2>']
Definition at line 193 of file plot_gmm_feat_extended.py.
filesFeat_1
plot_gmm_feat_extended.filesFeat_1 = args['<file-feat-1>']
Definition at line 194 of file plot_gmm_feat_extended.py.
filesFeat_2
plot_gmm_feat_extended.filesFeat_2 = args['<file-feat-2>']
Definition at line 195 of file plot_gmm_feat_extended.py.
limits
list plot_gmm_feat_extended.limits = args['--limits']
Definition at line 204 of file plot_gmm_feat_extended.py.
percents
plot_gmm_feat_extended.percents = args['--percents']
Definition at line 198 of file plot_gmm_feat_extended.py.
USAGE
string plot_gmm_feat_extended.USAGE
Initial value:
 = '''
 Draws the regions in space covered with a certain probability by a GMM.
 Usage:
     plot_gmm_feat_extended [--help|-h] [options] <file-gmm-1> [<file-feat-1>] [<file-gmm-2>] [<file-feat-2>]
 Options:
     --yDim INT, -x INT               'x' dimension to use from GMM and feature vectors [default: 0]
     --xDim INT, -y INT               'y' dimension to use from GMM and feature vectors [default: 1]
     --percents FLOAT..., -p FLOAT...  Percentages covered by the regions [default: 90,50]
     --colorGMM STR, -g STR            Color of the GMM regions boundaries [default: red]
     --colorFEAT STR, -f STR           Color of the feature population [default: red]
     --limits xyLimits -l xyLimits     xyLimits are the four values xMin,xMax,yMin,yMax [default: auto]
     --help, -h                        Shows this message
 Arguments:
     <file-gmm-1>    File with the first Gaussian mixture model to be plotted
     <file-feat-1>   Feature files to be plotted along the first GMM
     <file-gmm-2>    File with the second Gaussian mixture model to be plotted
     <file-feat-2>   Feature files to be plotted along the second GMM
 '''
Main Program.
Definition at line 165 of file plot_gmm_feat_extended.py.
xDim
plot_gmm_feat_extended.xDim = int(args['--xDim'])
Definition at line 196 of file plot_gmm_feat_extended.py.
yDim
plot_gmm_feat_extended.yDim = int(args['--yDim'])
Definition at line 197 of file plot_gmm_feat_extended.py.