Pr치ctica 4 de PAV - reconocimiento y verificaci칩n del locutor: upc::GMM Class Reference
upc::GMM Class Reference
#include "gmm.h"
Public Member Functions
GMM ()
Default contructor.
void resize (size_t _nmix, size_t dim)
void delete_mixture (unsigned int k)
Delete mixture k.
int random_init (const upc::fmatrix &data, unsigned int nmix)
Create GMM with nmix mixture assigning randomly vectors to each mixture.
int vq_lbg (const upc::fmatrix &data, unsigned int final_nmix, unsigned int max_it, float inc_threshold, int verbose)
Create GMM with nmix using vector quantizer dessign (Splitting + Lloyd)
int em (const upc::fmatrix &data, unsigned int max_it, float inc_prob_threshold, int verbose)
EM: reestimate GMM from data (given initial value of gmm)
int em_split (const upc::fmatrix &data, unsigned int nmix, unsigned int max_it, float inc_prob_threshold, int verbose)
Starts with gmm size 1, then split gmm size 2 and apply em, then gmm size 4 and EM, etc. till arrive to gmm of size nmix.
float logprob (const upc::fmatrix &data) const
Compute log10(prob)/n of the sequence of data; data[0] .... data[n-1]; n= data.size()
std::istream & read (std::istream &)
std::ostream & write (std::ostream &) const
read gmm from binary file
std::ostream & print (std::ostream &) const
write gmm into binary file
Protected Member Functions
float gmm_logprob (const float *x) const
compute logprob of input vector x
float em_expectation (const upc::fmatrix &data, upc::fmatrix &weights) const
int em_maximization (const upc::fmatrix &data, const upc::fmatrix &weights)
int centroid (const upc::fmatrix &data)
Create GMM with one mixture, centroid of data.
int split (unsigned int target_size)
Split each mixture in two to go towards the target_size.
void split_mixture (unsigned int src, unsigned int dest)
Split a mixture into two close mixtures.
int vq_lloyd (const fmatrix &data, unsigned int max_it, float inc_threshold, int verbose)
Design vector quantizer from data.
float vq_expectation (const fmatrix &data, ivector &indexes) const
int vq_maximization (const fmatrix &data, const ivector &indexes, bool update_variances)
float vq (const float *x, int &index) const
Quantize input data: find the closest codevector (mixture) to input vector x and save in index.
float vq_distance (const float *x, const float *y) const
Distance to compare input data and codevectors.
int vq_split (unsigned int target_size)
Split each codevector in two, to go towards the target_size.
void vq_split_centroid (unsigned int n_src, unsigned int n_dest)
Split one codevector in two close ones.
Protected Attributes
size_t vector_size
size of each input data (num. parameters)
size_t nmix
number of mixtures in the GMM
upc::fvector w
w[i]: weight of Mixture i
upc::fmatrix mu
mu[i]: mean of Mixture i (vector: mu[i][0] ... mu[i][vector_size-1])
upc::fmatrix inv_sigma
inv_sigma[i]: inverse of sigma of mixture i (vector, assuming diagonal covariance)
upc::fvector global_inv_sigma
used in vq, to define weighted euclidean distance
Detailed Description
Definition at line 40 of file gmm.h.
Constructor & Destructor Documentation
GMM()
upc::GMM::GMM () inline
Default contructor.
Definition at line 57 of file gmm.h.
References nmix, and vector_size.
Member Function Documentation
centroid()
int upc::GMM::centroid (const upc::fmatrix & data) protected
Create GMM with one mixture, centroid of data.
Definition at line 120 of file gmm.cpp.
References spk_verif_score::n, upc::matrix< _Ty >::ncol(), and upc::matrix< _Ty >::nrow().
delete_mixture()
void upc::GMM::delete_mixture (unsigned int k)
Delete mixture k.
Definition at line 71 of file gmm.cpp.
References run_spkid::w.
em()
int upc::GMM::em (const upc::fmatrix & data, unsigned int max_it, float inc_prob_threshold, int verbose)
EM: reestimate GMM from data (given initial value of gmm)
TODO:
[HECHO]:
Definition at line 200 of file gmm.cpp.
References upc::matrix< _Ty >::nrow().
Referenced by main().
em_expectation()
float upc::GMM::em_expectation (const upc::fmatrix & data, upc::fmatrix & weights) const protected
Intermediate steps in EM: expectation: For each vector data[n], and for each mixture i=0..nmix-1, estimate weights[n][i] with probability that data 'n' "belongs" to mixture 'i'
For each input data compute the probability that the data is generated from each mixture We work with log of probabilities to avoid numerical problems on intermediate results
Definition at line 170 of file gmm.cpp.
References upc::add_logs(), upc::gaussian_logprob(), spk_verif_score::n, upc::matrix< _Ty >::ncol(), upc::matrix< _Ty >::nrow(), upc::matrix< _Ty >::resize(), and run_spkid::w.
em_maximization()
int upc::GMM::em_maximization (const upc::fmatrix & data, const upc::fmatrix & weights) protected
Intermediate steps in EM: maximization: Given the vector data[n], and the weights[n][i] for each vector n, and mixture i, re-estimate the parameters of each mixture: constant w[i] mean vector mu[i] variance information: inv_sigma[j] (vector as we assume diagonal covariance matrix; inverse values stored)
Compute the best mixtures (weights, means, variances) given -the input data -the weights that the input data is generated for each gaussian
Definition at line 140 of file gmm.cpp.
References spk_verif_score::n, upc::matrix< _Ty >::nrow(), and run_spkid::w.
em_split()
int upc::GMM::em_split (const upc::fmatrix & data, unsigned int nmix, unsigned int max_it, float inc_prob_threshold, int verbose)
Starts with gmm size 1, then split gmm size 2 and apply em, then gmm size 4 and EM, etc. till arrive to gmm of size nmix.
Definition at line 229 of file gmm.cpp.
References anonymous_namespace{docopt_util.h}::split().
Referenced by main().
gmm_logprob()
float upc::GMM::gmm_logprob (const float * x) const protected
compute logprob of input vector x
Computes the logprob of a single frame of the input data.
Definition at line 91 of file gmm.cpp.
References upc::add_logs(), upc::gaussian_logprob(), and run_spkid::w.
logprob()
float upc::GMM::logprob (const upc::fmatrix & data) const
Compute log10(prob)/n of the sequence of data; data[0] .... data[n-1]; n= data.size()
TODO:
[HECHO]:
Compute the logprob for the whole input data.
TODO:
[HECHO]:
Compute the logprob of a single frame of the input data; you can use gmm_logprob() above.
Definition at line 104 of file gmm.cpp.
References spk_verif_score::n, upc::matrix< _Ty >::ncol(), and upc::matrix< _Ty >::nrow().
Referenced by verify().
print()
std::ostream & upc::GMM::print (std::ostream & os) const
write gmm into binary file
Definition at line 316 of file gmm.cpp.
References run_spkid::w.
Referenced by main().
random_init()
int upc::GMM::random_init (const upc::fmatrix & data, unsigned int nmix)
Create GMM with nmix mixture assigning randomly vectors to each mixture.
Estimate GMM with nmix mixtures from data. Apply splitting (centroid, 2, 4, ... nmix) Iterate till prob. does not improve more than prob_threshold or max_it. verbose=1 => show iteration probaility in stdout
Definition at line 278 of file gmm.cpp.
References spk_verif_score::n, upc::matrix< _Ty >::ncol(), upc::matrix< _Ty >::nrow(), and upc::matrix< _Ty >::reset().
Referenced by main().
read()
std::istream & upc::GMM::read (std::istream & is)
Definition at line 299 of file gmm.cpp.
References upc::header, HEADER_SIZE, and run_spkid::w.
Referenced by operator>>().
resize()
void upc::GMM::resize (size_t _nmix, size_t dim)
Define num. of mixtures and size of input samples (num. param.) The new gmm includes the old values and zeros, for the new ones
Definition at line 19 of file gmm.cpp.
References spk_verif_score::n, and run_spkid::w.
split()
int upc::GMM::split (unsigned int target_size) protected
Split each mixture in two to go towards the target_size.
Definition at line 256 of file gmm.cpp.
split_mixture()
void upc::GMM::split_mixture (unsigned int src, unsigned int dest) protected
Split a mixture into two close mixtures.
Definition at line 238 of file gmm.cpp.
References run_spkid::w.
vq()
float GMM::vq (const float * x, int & index) const protected
Quantize input data: find the closest codevector (mixture) to input vector x and save in index.
Definition at line 91 of file gmm_vq.cpp.
vq_distance()
float GMM::vq_distance (const float * x, const float * y) const protected
Distance to compare input data and codevectors.
Definition at line 64 of file gmm_vq.cpp.
vq_expectation()
float GMM::vq_expectation (const fmatrix & data, ivector & indexes) const protected
Intermediate steps in vq estimation: vq_expectation. For each vector data[n], selects the closer mixture (mean) and save in indexes[n]
Definition at line 109 of file gmm_vq.cpp.
References spk_verif_score::n, upc::matrix< _Ty >::ncol(), and upc::matrix< _Ty >::nrow().
vq_lbg()
int GMM::vq_lbg (const upc::fmatrix & data, unsigned int final_nmix, unsigned int max_it, float inc_threshold, int verbose)
Create GMM with nmix using vector quantizer dessign (Splitting + Lloyd)
Definition at line 14 of file gmm_vq.cpp.
Referenced by main().
vq_lloyd()
int GMM::vq_lloyd (const fmatrix & data, unsigned int max_it, float inc_threshold, int verbose) protected
Design vector quantizer from data.
Definition at line 169 of file gmm_vq.cpp.
References upc::matrix< _Ty >::nrow().
vq_maximization()
int GMM::vq_maximization (const fmatrix & data, const ivector & indexes, bool update_variances) protected
Intermediate steps in vq estimation: vq_maximization. re-estimate the codewords (mean of mixtures). The mean mu[j] is updated using the vectors data[n] such dat indexes[n] is 'j' If update_variances is true, then the variances inv_sigma[j] is computed
Definition at line 126 of file gmm_vq.cpp.
References MIN_MEMBERS, spk_verif_score::n, upc::matrix< _Ty >::nrow(), and run_spkid::w.
vq_split()
int GMM::vq_split (unsigned int target_size) protected
Split each codevector in two, to go towards the target_size.
Definition at line 30 of file gmm_vq.cpp.
vq_split_centroid()
void GMM::vq_split_centroid (unsigned int n_src, unsigned int n_dest) protected
Split one codevector in two close ones.
Definition at line 48 of file gmm_vq.cpp.
References run_spkid::w.
write()
std::ostream & upc::GMM::write (std::ostream & os) const
read gmm from binary file
Definition at line 310 of file gmm.cpp.
References upc::header, HEADER_SIZE, and run_spkid::w.
Referenced by operator<<().
Member Data Documentation
global_inv_sigma
upc::fvector upc::GMM::global_inv_sigma protected
used in vq, to define weighted euclidean distance
Definition at line 51 of file gmm.h.
inv_sigma
upc::fmatrix upc::GMM::inv_sigma protected
inv_sigma[i]: inverse of sigma of mixture i (vector, assuming diagonal covariance)
Definition at line 49 of file gmm.h.
mu
upc::fmatrix upc::GMM::mu protected
mu[i]: mean of Mixture i (vector: mu[i][0] ... mu[i][vector_size-1])
Definition at line 48 of file gmm.h.
nmix
size_t upc::GMM::nmix protected
number of mixtures in the GMM
Definition at line 46 of file gmm.h.
Referenced by GMM().
vector_size
size_t upc::GMM::vector_size protected
size of each input data (num. parameters)
GMM: sum of nmix gaussians, to model vectors of vector_size coefficients Each gaussian, i, has parameters w[i], mu[i][l], inv_sigma[i][l]
Definition at line 45 of file gmm.h.
Referenced by GMM().
w
upc::fvector upc::GMM::w protected
w[i]: weight of Mixture i
Definition at line 47 of file gmm.h.
The documentation for this class was generated from the following files:
/Users/davidbonet/Desktop/P4/src/include/gmm.h
/Users/davidbonet/Desktop/P4/src/pav/gmm.cpp
/Users/davidbonet/Desktop/P4/src/pav/gmm_vq.cpp