Pr치ctica 4 de PAV - reconocimiento y verificaci칩n del locutor: wav2lp Namespace Reference
wav2lp Namespace Reference
Variables
base = /tmp/$(basename $0).$$
int lpc_order = $1
int inputfile = $2
int outputfile = $3
int UBUNTU_SPTK = 0
string X2X = "sptk x2x"
string FRAME = "sptk frame"
string WINDOW = "sptk window"
string LPC = "sptk lpc"
ncol = $((lpc_order+1))
LP #####################################.
string nrow = `$X2X +fa < $base.lp | wc -l | perl -ne 'print $_/'$ncol', "\n";'`
Variable Documentation
base
wav2lp.base = /tmp/$(basename $0).$$
Definition at line 9 of file wav2lp.sh.
FRAME
string wav2lp.FRAME = "sptk frame"
Definition at line 30 of file wav2lp.sh.
inputfile
int wav2lp.inputfile = $2
Definition at line 23 of file wav2lp.sh.
LPC
string wav2lp.LPC = "sptk lpc"
Definition at line 32 of file wav2lp.sh.
lpc_order
int wav2lp.lpc_order = $1
Definition at line 22 of file wav2lp.sh.
ncol
wav2lp.ncol = $((lpc_order+1))
LP #####################################.
Definition at line 51 of file wav2lp.sh.
Referenced by main(), upc.operator<<(), upc.operator>>(), MyFMatrix.print(), and read_data().
nrow
string wav2lp.nrow = `$X2X +fa < $base.lp | wc -l | perl -ne 'print $_/'$ncol', "\n";'`
Definition at line 52 of file wav2lp.sh.
Referenced by upc.operator<<(), upc.operator>>(), MyFMatrix.print(), and read_data().
outputfile
int wav2lp.outputfile = $3
Definition at line 24 of file wav2lp.sh.
UBUNTU_SPTK
int wav2lp.UBUNTU_SPTK = 0
Definition at line 26 of file wav2lp.sh.
WINDOW
string wav2lp.WINDOW = "sptk window"
Definition at line 31 of file wav2lp.sh.
X2X
string wav2lp.X2X = "sptk x2x"
Definition at line 29 of file wav2lp.sh.