Pr치ctica 4 de PAV - reconocimiento y verificaci칩n del locutor: /Users/davidbonet/Desktop/P4/src/pearson/pearson.cpp File Reference
pearson.cpp File Reference
#include <unistd.h>
#include <iostream>
#include <fstream>
#include <algorithm>
#include <utility>
#include <stdlib.h>
#include <math.h>
#include "filename.h"
#include "matrix.h"
Classes
class MyFMatrix
Functions
ostream & operator<< (ostream &os, const MyFMatrix &dat)
int read_data (const vector< string > &filenames, fmatrix &dat)
int usage (const char *progname, int err)
int read_options (int ArgC, const char *ArgV[], vector< string > &filenames, Filename &cov_filename, Filename &covnorm_filename, bool &binary)
bool compare_corr (pair< int, float > a, pair< int, float > b)
void report_pearson (ostream &os, const fmatrix &sigma)
void normalize_covarianze (fmatrix &cov)
void covarianze (const fmatrix &dat, fmatrix &cov)
int main (int argc, const char *argv[])
Function Documentation
compare_corr()
bool compare_corr (pair< int, float > a, pair< int, float > b)
Definition at line 54 of file pearson.cpp.
Referenced by report_pearson().
covarianze()
void covarianze (const fmatrix & dat, fmatrix & cov)
Definition at line 97 of file pearson.cpp.
References spk_verif_score::n, upc::matrix< _Ty >::ncol(), upc::matrix< _Ty >::nrow(), and upc::matrix< _Ty >::resize().
Referenced by main().
main()
int main (int argc, const char * argv[])
Read command line options
Definition at line 119 of file pearson.cpp.
References upc::Filename::checkDir(), covarianze(), upc::matrix< _Ty >::ncol(), normalize_covarianze(), upc::matrix< _Ty >::nrow(), read_data(), read_options(), report_pearson(), and usage().
normalize_covarianze()
void normalize_covarianze (fmatrix & cov)
Definition at line 79 of file pearson.cpp.
References upc::matrix< _Ty >::ncol(), and upc::matrix< _Ty >::nrow().
Referenced by main().
operator<<()
ostream& operator<< (ostream & os, const MyFMatrix & dat)
Definition at line 40 of file pearson.cpp.
References MyFMatrix::print().
read_data()
int read_data (const vector< string > & filenames, fmatrix & dat)
Definition at line 211 of file pearson.cpp.
References upc::matrix< _Ty >::ncol(), upc::matrix< _Ty >::nrow(), upc::matrix< _Ty >::reset(), and upc::matrix< _Ty >::resize().
Referenced by main().
read_options()
int read_options (int ArgC, const char * ArgV[], vector< string > & filenames, Filename & cov_filename, Filename & covnorm_filename, bool & binary)
Definition at line 178 of file pearson.cpp.
Referenced by main().
report_pearson()
void report_pearson (ostream & os, const fmatrix & sigma)
Definition at line 58 of file pearson.cpp.
References compare_corr(), and upc::matrix< _Ty >::ncol().
Referenced by main().
usage()
int usage (const char * progname, int err)
Definition at line 163 of file pearson.cpp.
Referenced by main().